language: ruby
sudo: false
cache: bundler
before_script: bundle install --jobs=3 --retry=3

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6

gemfile:
  - gemfiles/Gemfile.rails-4-2-stable
  - gemfiles/Gemfile.rails-5-0-stable
  - gemfiles/Gemfile.rails-5-1-stable
  - gemfiles/Gemfile.rails-5-2-stable

matrix:
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/Gemfile.rails-4-2-stable
